name: "Build waydroid flavor"
on:
  workflow_dispatch:
jobs:
  build-waydroid-flavor:
    strategy:
      matrix:
        arch:
          - x86_64
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-21.11
        install_url: https://releases.nixos.org/nix/nix-2.7.0/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          substituters = https://cache.nixos.org ${{ secrets.CACHE_BUCKET_URL }} https://robotnix.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ${{ secrets.CACHE_PUBLIC_KEY }} robotnix.cachix.org-1:+y88eX6KTvkJyernp1knbpttlaLTboVp4vq/b24BIv0=
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Build
      run: |
        STORE_PATH="$(nix-build --arg configuration '{ device="${{ matrix.arch }}"; flavor="waydroid"; }' -A config.build.waydroid)"
        echo "STORE_PATH=${STORE_PATH}" >> "$GITHUB_ENV"
    - name: Push to cache bucket
      run: |
        echo ${{ secrets.CACHE_PRIVATE_KEY }} > /tmp/cache-priv-key.pem
        nix store sign --key-file /tmp/cache-priv-key.pem "$STORE_PATH"
        nix copy --to ${{ secrets.CACHE_BUCKET_URL }} "$STORE_PATH"
